const defaultImage = (src: string) => {
  const img = new window.Image()
  img.src = src
  return img
}
const dusj = '/icons/dusj.png'
const elbil = '/icons/elbil.png'
const forbruk = '/icons/forbruk.png'
const kaffetrakter = '/icons/kaffetrakter.png'
const oppvarming = '/icons/oppvarming.png'
const oppvaskmaskin = '/icons/oppvaskmaskin.png'
const stekeovnplate = '/icons/stekeovn-plate.png'
const vaskemaskin = '/icons/vaskemaskin.png'

export const DEFAULT_DAG = [
  {
    x: 0,
    y: 280,
    width: 147.5,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: 'zz4usc',
    draggable: false,
    isDragging: false,
    wattage: 1438,
    minWatt: 1000,
    maxWatt: 3500,
    name: 'Oppvarming',
    description: 'Oppvarming',
    image: defaultImage(oppvarming),
  },
  {
    x: 147.5,
    y: 280,
    width: 590,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: 'oma0xc',
    draggable: false,
    isDragging: false,
    wattage: 2888,
    minWatt: 1000,
    maxWatt: 3500,
    name: 'Oppvarming',
    description: 'Oppvarming',
    image: defaultImage(oppvarming),
  },
  {
    x: 737.5,
    y: 280,
    width: 147.5,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: 'mqj6ao',
    draggable: false,
    isDragging: false,
    wattage: 1804,
    minWatt: 1000,
    maxWatt: 3500,
    name: 'Oppvarming',
    description: 'Lamper',
    image: defaultImage(oppvarming),
  },
  {
    x: 221.25,
    y: 40,
    width: 73.75,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: '0yia4',
    draggable: false,
    isDragging: false,
    wattage: 1500,
    minWatt: 500,
    maxWatt: 1800,
    name: 'Kaffemaskin',
    description: 'Kaffemaskin',
    image: defaultImage(kaffetrakter),
  },
  {
    x: 258.125,
    y: 80,
    width: 73.75,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: 'dbe2vb',
    draggable: false,
    isDragging: false,
    wattage: 2000,
    minWatt: 1000,
    maxWatt: 3000,
    name: 'Varmtvannstank',
    description: 'Varmtvannstank',
    image: defaultImage(forbruk),
  },
  {
    x: 0,
    y: 200,
    width: 221.25,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: '9ub8w9r',
    draggable: false,
    isDragging: false,
    wattage: 6338,
    minWatt: 2500,
    maxWatt: 9500,
    name: 'Elbil-lading',
    description: 'Elbil-lading',
    image: defaultImage(elbil),
  },
  {
    x: 626.875,
    y: 80,
    width: 221.25,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: '3wd8n6',
    draggable: false,
    isDragging: false,
    wattage: 150,
    minWatt: 50,
    maxWatt: 200,
    name: 'TV',
    description: 'Varmepumpe',
    image: defaultImage(forbruk),
  },
  {
    x: 184.375,
    y: 120,
    width: 147.5,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: 'maewds',
    draggable: false,
    isDragging: false,
    wattage: 88,
    minWatt: 20,
    maxWatt: 100,
    name: 'Lamper',
    description: 'Lamper',
    image: defaultImage(forbruk),
  },
  {
    x: 590,
    y: 120,
    width: 295,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: 'fibrua',
    draggable: false,
    isDragging: false,
    wattage: 95,
    minWatt: 20,
    maxWatt: 100,
    name: 'Lamper',
    description: 'Lamper',
    image: defaultImage(forbruk),
  },
  {
    x: 737.5,
    y: 200,
    width: 147.5,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: 'hlacwv',
    draggable: false,
    isDragging: false,
    wattage: 6455,
    minWatt: 2500,
    maxWatt: 9500,
    name: 'Elbil-lading',
    description: 'Elbil-lading',
    image: defaultImage(elbil),
  },
  {
    x: 331.875,
    y: 200,
    width: 110.625,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: 'zj6348',
    draggable: false,
    isDragging: false,
    wattage: 2000,
    minWatt: 1000,
    maxWatt: 3000,
    name: 'Vaskemaskin',
    description: 'Vaskemaskin',
    image: defaultImage(vaskemaskin),
  },
  {
    x: 442.5,
    y: 200,
    width: 110.625,
    height: 40,
    stroke: '#FFF7EB',
    strokeWidth: 5,
    strokeScaleEnabled: false,
    fill: '#CAE3D2',
    id: 'w6mh5u',
    draggable: false,
    isDragging: false,
    wattage: 3000,
    minWatt: 1500,
    maxWatt: 3500,
    name: 'Tørketrommel',
    description: 'Tørketrommel',
    image: defaultImage(vaskemaskin),
  },
]
